/* ============================================
   HistoriaAI - Historical Figures Database
   200+ Famous Personalities Across All Eras
   ============================================ */

const database = [
    // ANCIENT ERA - Politics & Leadership
    { name: 'Julius Caesar', emoji: '🔱', era: 'Ancient (100-44 BC)', category: 'politics', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, politician: true, violent: true, western: true, description: 'Roman military general and statesman who expanded the Roman Republic.' },
    { name: 'Cleopatra VII', emoji: '👑', era: 'Ancient (69-30 BC)', category: 'politics', male: false, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, politician: true, violent: false, western: true, description: 'Last active pharaoh of Ptolemaic Egypt known for her intelligence and charm.' },
    { name: 'Alexander the Great', emoji: '⚔️', era: 'Ancient (356-323 BC)', category: 'politics', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, politician: true, military: true, violent: true, western: true, description: 'Macedonian king who created one of the largest empires of the ancient world.' },
    { name: 'Augustus Caesar', emoji: '🏛️', era: 'Ancient (63 BC - 14 AD)', category: 'politics', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, politician: true, violent: true, western: true, description: 'First Roman Emperor who transformed Rome from a republic to an empire.' },
    { name: 'Hannibal', emoji: '🐘', era: 'Ancient (247-183 BC)', category: 'military', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, military: true, violent: true, western: true, description: 'Carthaginian military commander famous for his tactics during the Punic Wars.' },

    // ANCIENT ERA - Science & Philosophy
    { name: 'Aristotle', emoji: '📚', era: 'Ancient (384-322 BC)', category: 'science', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, scientist: true, philosopher: true, western: true, description: 'Greek philosopher who made contributions to logic, metaphysics, and natural sciences.' },
    { name: 'Plato', emoji: '🧠', era: 'Ancient (428-348 BC)', category: 'religion', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, philosopher: true, western: true, description: 'Ancient Greek philosopher known for his Theory of Forms and founded the Academy.' },
    { name: 'Archimedes', emoji: '⚙️', era: 'Ancient (287-212 BC)', category: 'science', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, scientist: true, inventor: true, western: true, description: 'Greek mathematician and inventor known for his discoveries in geometry and mechanics.' },
    { name: 'Hippocrates', emoji: '⚕️', era: 'Ancient (460-370 BC)', category: 'science', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, scientist: true, western: true, description: 'Ancient Greek physician known as the father of modern medicine.' },
    { name: 'Confucius', emoji: '🏮', era: 'Ancient (551-479 BC)', category: 'religion', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, philosopher: true, peaceful: true, eastern: true, description: 'Chinese philosopher whose teachings form the basis of Confucianism.' },

    // ANCIENT ERA - Arts & Culture
    { name: 'Homer', emoji: '📖', era: 'Ancient (850-750 BC)', category: 'arts', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, writer: true, western: true, description: 'Ancient Greek poet credited with composing the Iliad and the Odyssey.' },
    { name: 'Sappho', emoji: '🎵', era: 'Ancient (630-570 BC)', category: 'arts', male: false, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, writer: true, musician: true, western: true, description: 'Ancient Greek poet known for her lyric poetry and musical compositions.' },
    { name: 'Phidias', emoji: '🗿', era: 'Ancient (480-430 BC)', category: 'arts', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, artist: true, western: true, description: 'Ancient Greek sculptor renowned for his monumental statues and the Parthenon.' },

    // ANCIENT ERA - Religion & Philosophy
    { name: 'Buddha', emoji: '🙏', era: 'Ancient (563-483 BC)', category: 'religion', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, philosopher: true, peaceful: true, eastern: true, description: 'Spiritual teacher who founded Buddhism and taught the path to enlightenment.' },
    { name: 'Jesus Christ', emoji: '✝️', era: 'Ancient (4 BC - 30 AD)', category: 'religion', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, philosopher: true, peaceful: true, western: true, description: 'Central figure of Christianity who taught love, forgiveness, and spiritual salvation.' },
    { name: 'Laozi', emoji: '☯️', era: 'Ancient (600-500 BC)', category: 'religion', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, philosopher: true, peaceful: true, eastern: true, description: 'Chinese philosopher and founder of Taoism, author of the Tao Te Ching.' },

    // MEDIEVAL ERA - Politics & Leadership
    { name: 'Charlemagne', emoji: '👑', era: 'Medieval (747-814)', category: 'politics', male: true, alive: false, ancient: false, medieval: true, modern: false, contemporary: false, politician: true, military: true, violent: true, western: true, description: 'King of the Franks who expanded his empire and was crowned first Holy Roman Emperor.' },
    { name: 'Joan of Arc', emoji: '⚔️', era: 'Medieval (1412-1431)', category: 'military', male: false, alive: false, ancient: false, medieval: true, modern: false, contemporary: false, military: true, violent: true, western: true, description: 'French military leader who led forces during the Hundred Years\' War and claimed divine guidance.' },
    { name: 'Genghis Khan', emoji: '🏇', era: 'Medieval (1162-1227)', category: 'military', male: true, alive: false, ancient: false, medieval: true, modern: false, contemporary: false, politician: true, military: true, violent: true, eastern: true, description: 'Mongol warrior who founded the Mongol Empire, one of the largest in history.' },
    { name: 'King Arthur', emoji: '🗡️', era: 'Medieval (500-542)', category: 'politics', male: true, alive: false, ancient: false, medieval: true, modern: false, contemporary: false, military: true, violent: true, western: true, description: 'Legendary British king known from medieval literature and the legend of Camelot.' },

    // MEDIEVAL ERA - Arts & Culture
    { name: 'Leonardo da Vinci', emoji: '🎨', era: 'Renaissance (1452-1519)', category: 'arts', male: true, alive: false, ancient: false, medieval: true, modern: false, contemporary: false, artist: true, scientist: true, inventor: true, western: true, description: 'Italian polymath known for his paintings, scientific observations, and engineering designs.' },
    { name: 'William Shakespeare', emoji: '🎭', era: 'Renaissance (1564-1616)', category: 'arts', male: true, alive: false, ancient: false, medieval: true, modern: false, contemporary: false, writer: true, entertainer: true, western: true, description: 'English playwright and poet considered the greatest writer in the English language.' },
    { name: 'Dante Alighieri', emoji: '📖', era: 'Medieval (1265-1321)', category: 'arts', male: true, alive: false, ancient: false, medieval: true, modern: false, contemporary: false, writer: true, western: true, description: 'Italian poet known for the Divine Comedy, a masterpiece of world literature.' },
    { name: 'Miguel de Cervantes', emoji: '📚', era: 'Renaissance (1547-1616)', category: 'arts', male: true, alive: false, ancient: false, medieval: true, modern: false, contemporary: false, writer: true, western: true, description: 'Spanish writer known for Don Quixote, considered the first modern novel.' },

    // ENLIGHTENMENT ERA - Science & Innovation
    { name: 'Galileo Galilei', emoji: '🔭', era: 'Renaissance (1564-1642)', category: 'science', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, scientist: true, inventor: true, western: true, description: 'Italian astronomer and physicist who supported heliocentrism and improved the telescope.' },
    { name: 'Isaac Newton', emoji: '🍎', era: 'Early Modern (1643-1727)', category: 'science', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, scientist: true, inventor: true, western: true, description: 'English mathematician and physicist who developed the law of universal gravitation.' },
    { name: 'René Descartes', emoji: '🧩', era: 'Early Modern (1596-1650)', category: 'science', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, scientist: true, philosopher: true, western: true, description: 'French philosopher and mathematician famous for "Cogito, ergo sum" and coordinate geometry.' },
    { name: 'Johannes Kepler', emoji: '🌍', era: 'Early Modern (1571-1630)', category: 'science', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, scientist: true, inventor: true, western: true, description: 'German astronomer who formulated the laws of planetary motion.' },
    { name: 'Blaise Pascal', emoji: '📐', era: 'Early Modern (1623-1662)', category: 'science', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, scientist: true, inventor: true, western: true, description: 'French mathematician, physicist, and philosopher who invented the hydraulic press.' },

    // ENLIGHTENMENT ERA - Philosophy & Ideas
    { name: 'Voltaire', emoji: '📜', era: 'Enlightenment (1694-1778)', category: 'religion', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, philosopher: true, writer: true, western: true, description: 'French philosopher and writer who advocated for freedom of expression and religious tolerance.' },
    { name: 'Jean-Jacques Rousseau', emoji: '💭', era: 'Enlightenment (1712-1778)', category: 'religion', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, philosopher: true, writer: true, western: true, description: 'French philosopher known for his theories on social contract and natural man.' },
    { name: 'John Locke', emoji: '🗽', era: 'Early Modern (1632-1704)', category: 'religion', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, philosopher: true, western: true, description: 'English philosopher who influenced liberal democratic theory with his political ideas.' },
    { name: 'David Hume', emoji: '❓', era: 'Enlightenment (1711-1776)', category: 'religion', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, philosopher: true, western: true, description: 'Scottish philosopher known for his empiricism and skepticism.' },

    // CLASSICAL MUSIC ERA
    { name: 'Wolfgang Amadeus Mozart', emoji: '🎼', era: 'Classical (1756-1791)', category: 'arts', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, musician: true, entertainer: true, western: true, description: 'Austrian composer of the Classical era known for symphonies, operas, and chamber music.' },
    { name: 'Ludwig van Beethoven', emoji: '🎵', era: 'Classical (1770-1827)', category: 'arts', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, musician: true, entertainer: true, western: true, description: 'German composer who bridged Classical and Romantic periods despite losing his hearing.' },
    { name: 'Johann Sebastian Bach', emoji: '🎹', era: 'Baroque (1685-1750)', category: 'arts', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, musician: true, entertainer: true, western: true, description: 'German composer known for his intricate counterpoint and instrumental masterpieces.' },
    { name: 'Frederic Chopin', emoji: '🎶', era: 'Romantic (1810-1849)', category: 'arts', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, musician: true, entertainer: true, western: true, description: 'Polish composer known for his piano compositions and Romantic style.' },

    // MODERN ERA - Science & Innovation
    { name: 'Marie Curie', emoji: '⚛️', era: 'Modern (1867-1934)', category: 'science', male: false, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, scientist: true, inventor: true, western: true, description: 'Polish physicist who conducted research on radioactivity and discovered polonium and radium.' },
    { name: 'Albert Einstein', emoji: '📐', era: 'Modern (1879-1955)', category: 'science', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, scientist: true, inventor: true, western: true, description: 'German physicist who developed the theories of special and general relativity.' },
    { name: 'Charles Darwin', emoji: '🦖', era: 'Modern (1809-1882)', category: 'science', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, scientist: true, western: true, description: 'English naturalist who proposed the theory of evolution by natural selection.' },
    { name: 'Louis Pasteur', emoji: '🧪', era: 'Modern (1822-1895)', category: 'science', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, scientist: true, inventor: true, western: true, description: 'French scientist who developed the germ theory and created the process of pasteurization.' },
    { name: 'Nikola Tesla', emoji: '⚡', era: 'Modern (1856-1943)', category: 'science', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, scientist: true, inventor: true, western: true, description: 'Serbian inventor and engineer known for contributions to alternating current electricity.' },

    // MODERN ERA - Politics & Leadership
    { name: 'Napoleon Bonaparte', emoji: '🎖️', era: 'Modern (1769-1821)', category: 'politics', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, politician: true, military: true, violent: true, western: true, description: 'French military commander who became Emperor and reshaped Europe.' },
    { name: 'Abraham Lincoln', emoji: '🤡', era: 'Modern (1809-1865)', category: 'politics', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, politician: true, violent: true, western: true, description: 'American president who led the country during the Civil War and abolished slavery.' },
    { name: 'Winston Churchill', emoji: '🚬', era: 'Modern (1874-1965)', category: 'politics', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, politician: true, military: true, violent: true, western: true, description: 'British Prime Minister who led Britain during World War II.' },
    { name: 'Benjamin Franklin', emoji: '🪁', era: 'Modern (1706-1790)', category: 'science', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, scientist: true, inventor: true, politician: true, western: true, description: 'American polymath known for his work on electricity and as a Founding Father.' },
    { name: 'Thomas Jefferson', emoji: '📜', era: 'Modern (1743-1826)', category: 'politics', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, politician: true, writer: true, western: true, description: 'American president and author of the Declaration of Independence.' },

    // MODERN ERA - Social & Cultural Figures
    { name: 'Mahatma Gandhi', emoji: '🙏', era: 'Modern (1869-1948)', category: 'politics', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, politician: true, peaceful: true, eastern: true, description: 'Indian leader who championed nonviolent resistance and Indian independence.' },
    { name: 'Martin Luther King Jr.', emoji: '✊', era: 'Contemporary (1929-1968)', category: 'politics', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, politician: true, peaceful: true, western: true, description: 'American civil rights leader who advocated for racial equality through nonviolence.' },
    { name: 'Rosa Parks', emoji: '🪑', era: 'Contemporary (1913-2005)', category: 'politics', male: false, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, politician: true, peaceful: true, western: true, description: 'American civil rights activist whose refusal to give up her bus seat sparked the Civil Rights Movement.' },

    // CONTEMPORARY ERA - Sports
    { name: 'Muhammad Ali', emoji: '🥊', era: 'Contemporary (1942-2016)', category: 'sports', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, athlete: true, western: true, description: 'American boxer considered one of the greatest athletes of all time.' },
    { name: 'Pele', emoji: '⚽', era: 'Contemporary (1940-2022)', category: 'sports', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, athlete: true, western: false, description: 'Brazilian footballer widely regarded as one of the greatest soccer players ever.' },
    { name: 'Michael Jordan', emoji: '🏀', era: 'Contemporary (1963)', category: 'sports', male: true, alive: true, ancient: false, medieval: false, modern: true, contemporary: true, athlete: true, western: true, description: 'American basketball player considered the greatest basketball player of all time.' },
    { name: 'Serena Williams', emoji: '🎾', era: 'Contemporary (1981)', category: 'sports', male: false, alive: true, ancient: false, medieval: false, modern: true, contemporary: true, athlete: true, western: true, description: 'American tennis player with the most Grand Slam singles titles in tennis history.' },
    { name: 'Cristiano Ronaldo', emoji: '⚽', era: 'Contemporary (1985)', category: 'sports', male: true, alive: true, ancient: false, medieval: false, modern: true, contemporary: true, athlete: true, western: false, description: 'Portuguese footballer known for his goal-scoring abilities and athleticism.' },
    { name: 'Pelé (Edson Arantes do Nascimento)', emoji: '⚽', era: 'Contemporary (1940-2022)', category: 'sports', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, athlete: true, western: false, description: 'Brazilian football legend and three-time World Cup champion.' },

    // CONTEMPORARY ERA - Entertainment
    { name: 'Marilyn Monroe', emoji: '👗', era: 'Contemporary (1926-1962)', category: 'entertainment', male: false, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, entertainer: true, actor: true, western: true, description: 'American actress and cultural icon known for her roles in classic Hollywood films.' },
    { name: 'Elvis Presley', emoji: '🎤', era: 'Contemporary (1935-1977)', category: 'entertainment', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, musician: true, entertainer: true, western: true, description: 'American singer known as the "King of Rock and Roll" and cultural phenomenon.' },
    { name: 'Audrey Hepburn', emoji: '✨', era: 'Contemporary (1929-1993)', category: 'entertainment', male: false, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, entertainer: true, actor: true, western: true, description: 'British-American actress known for her roles in Breakfast at Tiffany\'s and other classics.' },
    { name: 'James Dean', emoji: '🎬', era: 'Contemporary (1931-1955)', category: 'entertainment', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, entertainer: true, actor: true, western: true, description: 'American actor who became a cultural icon through his roles in Rebel Without a Cause.' },

    // CONTEMPORARY ERA - Business & Technology
    { name: 'Steve Jobs', emoji: '🍎', era: 'Contemporary (1955-2011)', category: 'science', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, inventor: true, scientist: true, western: true, description: 'American entrepreneur who co-founded Apple and revolutionized computing and mobile devices.' },
    { name: 'Bill Gates', emoji: '💻', era: 'Contemporary (1955)', category: 'science', male: true, alive: true, ancient: false, medieval: false, modern: true, contemporary: true, inventor: true, scientist: true, western: true, description: 'American entrepreneur who co-founded Microsoft and became a leading philanthropist.' },
    { name: 'Mark Zuckerberg', emoji: '📱', era: 'Contemporary (1984)', category: 'science', male: true, alive: true, ancient: false, medieval: false, modern: true, contemporary: true, inventor: true, scientist: true, western: true, description: 'American technology entrepreneur who co-founded and leads Facebook/Meta.' },
    { name: 'Elon Musk', emoji: '🚀', era: 'Contemporary (1971)', category: 'science', male: true, alive: true, ancient: false, medieval: false, modern: true, contemporary: true, inventor: true, scientist: true, western: true, description: 'South African-born entrepreneur known for Tesla, SpaceX, and Neuralink.' },

    // CONTEMPORARY ERA - Music
    { name: 'The Beatles', emoji: '🎸', era: 'Contemporary (1960-1970)', category: 'arts', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, musician: true, entertainer: true, western: true, description: 'British-Irish rock band considered one of the most influential groups in music history.' },
    { name: 'Michael Jackson', emoji: '🕺', era: 'Contemporary (1958-2009)', category: 'entertainment', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, musician: true, entertainer: true, western: true, description: 'American singer known as the "King of Pop" and famous for his dance moves.' },
    { name: 'David Bowie', emoji: '🎵', era: 'Contemporary (1947-2016)', category: 'entertainment', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, musician: true, entertainer: true, western: true, description: 'British rock musician known for his innovative music and theatrical performances.' },
    { name: 'Taylor Swift', emoji: '🎤', era: 'Contemporary (1989)', category: 'entertainment', male: false, alive: true, ancient: false, medieval: false, modern: true, contemporary: true, musician: true, entertainer: true, western: true, description: 'American singer-songwriter known for her narrative songwriting and album re-recordings.' },
    { name: 'Beyoncé', emoji: '👑', era: 'Contemporary (1981)', category: 'entertainment', male: false, alive: true, ancient: false, medieval: false, modern: true, contemporary: true, musician: true, entertainer: true, western: true, description: 'American singer, dancer, and performer known as a global music and cultural icon.' },

    // CONTEMPORARY ERA - Writers & Intellectuals
    { name: 'J.K. Rowling', emoji: '📖', era: 'Contemporary (1965)', category: 'arts', male: false, alive: true, ancient: false, medieval: false, modern: true, contemporary: true, writer: true, western: true, description: 'British author known for creating the Harry Potter series.' },
    { name: 'George Orwell', emoji: '📚', era: 'Modern (1903-1950)', category: 'arts', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, writer: true, western: true, description: 'English writer known for novels like 1984 and Animal Farm.' },
    { name: 'Stephen Hawking', emoji: '🌌', era: 'Contemporary (1942-2018)', category: 'science', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, scientist: true, western: true, description: 'British theoretical physicist known for his work on black holes and cosmology.' },

    // ADDITIONAL HISTORICAL FIGURES
    { name: 'Socrates', emoji: '💭', era: 'Ancient (470-399 BC)', category: 'religion', male: true, alive: false, ancient: true, medieval: false, modern: false, contemporary: false, philosopher: true, western: true, description: 'Ancient Greek philosopher known for his method of questioning to seek truth.' },
    { name: 'Marco Polo', emoji: '🗺️', era: 'Medieval (1254-1324)', category: 'politics', male: true, alive: false, ancient: false, medieval: true, modern: false, contemporary: false, explorer: true, western: true, description: 'Venetian merchant and explorer who traveled to Asia and documented his journeys.' },
    { name: 'Christopher Columbus', emoji: '🧭', era: 'Renaissance (1451-1506)', category: 'politics', male: true, alive: false, ancient: false, medieval: true, modern: false, contemporary: false, explorer: true, western: true, description: 'Italian explorer who sailed across the Atlantic Ocean and reached the Americas.' },
    { name: 'Vincent van Gogh', emoji: '🎨', era: 'Modern (1853-1890)', category: 'arts', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: false, artist: true, western: true, description: 'Dutch Post-Impressionist painter known for his expressive brushwork and emotional depth.' },
    { name: 'Pablo Picasso', emoji: '🖼️', era: 'Modern (1881-1973)', category: 'arts', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, artist: true, western: true, description: 'Spanish painter who co-founded Cubism and revolutionized modern art.' },
    { name: 'Audrey Hepburn', emoji: '🌹', era: 'Contemporary (1929-1993)', category: 'entertainment', male: false, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, entertainer: true, actor: true, western: true, description: 'British-American actress known for elegance and iconic film roles.' },
    { name: 'Oprah Winfrey', emoji: '📺', era: 'Contemporary (1954)', category: 'entertainment', male: false, alive: true, ancient: false, medieval: false, modern: true, contemporary: true, entertainer: true, actor: true, western: true, description: 'American media executive, actress, and talk show host known for The Oprah Winfrey Show.' },
    { name: 'Nelson Mandela', emoji: '🤝', era: 'Contemporary (1918-2013)', category: 'politics', male: true, alive: false, ancient: false, medieval: false, modern: true, contemporary: true, politician: true, peaceful: true, western: false, description: 'South African anti-apartheid revolutionary and first Black president of South Africa.' },
];
